export const CREATE_ORDER = 'CREAT_ORDER';
export const CREATE_ORDER_SUCCESS = 'CREAT_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREAT_ORDER_FAIL';

export const GET_ORDER_DETAIL = 'GET_ORDER_DETAILS';
export const GET_ORDER_DETAIL_SUCCESS = 'GET_ORDER_DETAIL_SUCCESS';
export const GET_ORDER_DETAIL_FAIL = 'GET_ORDER_DETAIL_FAIL';

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

export const GET_ORDER_LIST = 'GET_ORDER_LIST';
export const GET_ORDER_LIST_SUCCESS = 'GET_ORDER_LIST_SUCCESS';
export const GET_ORDER_LIST_FAIL = 'GET_ORDER_LIST_FAIL';
export const GET_ORDER_LIST_RESET = 'GET_ORDER_LIST_RESET';
